### ISSUE TITLE
todo-core

### ISSUE THREAD

**Issue by piekie** [piekie/Sensors#1]
- [x] make the first part
- [x] make the second part
- [ ] create wiki
- [ ] add icon to app! 🙂
