### ISSUE TITLE
todo-refactor

### ISSUE THREAD

**Issue by piekie** [piekie/Sensors#2]
- [ ] migrate to fresh version of Butterknife
- [ ] rename xml-ids to ids that correspond with the page (fragment) they belong: "menu_seekbar" change to "first_menu_seekbar"
- [ ] completely rewrite ActionView class
- [ ] completely rewrite FirstFragment class
- [ ] completely rewrite Dumbo, World and DrawThread classes
- [ ] add comments
- [ ] replace existing ActionView updating logic in Menus
- [ ] **MVP**
- [x] refactor intersection logic
